receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - http://localhost:5173
            - http://127.0.0.1:5173
          allowed_headers:
            - "*"

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
